parameters:
#    jobeet.example.class: SfTuts\JobeetBundle\Example

services:
#    jobeet.example:
#        class: %jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
